### ISSUE TITLE
Flexible coarse channel parallelisation

### ISSUE THREAD

**Issue by robotopia** [steve-ord/MWACUtils#1]
1) Add user option to run beamformer on selected coarse channels
2) Run beamformer as 1 SLURM job (requesting 1 node) per coarse channel

**Comment by steve-ord** [comment]
This should almost work already
The beam former uses its MPI Rank to determine which channel it opens ....
So it can be run as a single job

**Comment by robotopia** [comment]
...kind of. At the moment, if you try to run the beamformer on, say, 5 nodes, you will only ever get coarse channels 1-5 (or 24-20, in the "reverse, casa gains" case?). Ultimately, we'd want to be able to say something like: Please run the beamformer on **this_list_of_coarse_channels**, on **this_number_of_nodes**. The beamformer should then efficiently assign different channels to different nodes. The _wrapper script_ would be responsible for choosing the number of channels per nodes to call make_beam with in a system- and resource-dependent way (in Galaxy's case, probably one node per coarse channel makes the most sense).

**Comment by robotopia** [comment]
Transferring issues to my personal issue tracker.
